### ISSUE TITLE
import goprocam error

### ISSUE THREAD

**Issue by gbaweja** [KonradIT/gopro-py-api#58]
ImportError: No Module named request

Can you please help with this error. I do not understand what is wrong.

I also did: pip install request, but that didn't solve the problem.

**Comment by KonradIT** [comment]
Library works with Python 3.6 and above.

**Comment by tacleur** [comment]
Hello everyone,

I worked for 4 months for make video and photo capture with your API but the problem is that python don't recognize goprocam. My error message : 

`Python 3.7.2 (default, Jan 17 2019, 14:20:11) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> 
>>> from goprocam import GoProCamera, constants
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'goprocam'
>>> 
`
Can someone help me ?

Thanks a lot !

**Comment by KonradIT** [comment]
You don't have goprocam installed.

**Comment by tacleur** [comment]
Hi,

Thanks for your answer.
I had installed several times your API but i have this message.
I had follow your install procedure and the terminal said sucessful.
(I'm working on Linux Raspberry pi).

Thanks for your help.

**Comment by KonradIT** [comment]
Even pip install goprocam?

**Comment by tacleur** [comment]
> 
> 
> Even pip install goprocam?

yes.
I'll do it again : 

`pi@pi:~ $ sudo pip install goprocam
Requirement already satisfied: goprocam in /usr/local/lib/python2.7/dist-packages/goprocam-3.0.1-py2.7.egg
pi@pi:~ $ pip install goprocam
Collecting goprocam
Installing collected packages: goprocam
Successfully installed goprocam-3.0.3
pi@pi:~ $ from goprocam import GoProCamera, constants
from: can't read /var/mail/goprocam
pi@pi:~ $ python3
Python 3.7.2 (default, Jan 17 2019, 14:20:11) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from goprocam import GoProCamera, constants
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'goprocam'
>>> 

`thanks for your help

**Comment by gbaweja** [comment]
you need to do..

sudo pip3 install goprocam

**Comment by tacleur** [comment]
hi,
thanks for your answer.

Unfortunately, it don't works. impossible ton install with pip3 : 

`pi@pi:~ $ sudo pip3 install goprocam
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting goprocam
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/goprocam/
Could not fetch URL https://pypi.org/simple/goprocam/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/goprocam/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)) - skipping
 Could not fetch URL https://www.piwheels.org/simple/goprocam/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='www.piwheels.org', port=443): Max retries exceeded with url: /simple/goprocam/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)) - skipping
  Could not find a version that satisfies the requirement goprocam (from versions: )
No matching distribution found for goprocam
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)) - skipping
Could not fetch URL https://www.piwheels.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='www.piwheels.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)) - skipping`

How pass this problem?

Thansk for your help;

**Comment by KonradIT** [comment]
Seems like the SSL is badly configured.

**Comment by tacleur** [comment]
How can i correct SSL ?

**Comment by tacleur** [comment]
I found the problem.
I erased all my raspberry and now it's works with pip3.
